name: CI

on: [ push ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/registrars/realtimeregister

    steps:
      - uses: actions/checkout@v3

      - name: Composer install --dev
        uses: php-actions/composer@v6

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.1
          path: modules/registrars/realtimeregister
          ignore: modules/registrars/realtimregister/vendor
          standard: PSR12