name: Test application

on: [ push ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Composer install --dev
        uses: php-actions/composer@v6
        with:
          working_dir: "modules/registrars/realtimeregister"

      - name: PHPUnit
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: WHMCS
        with:
          version: 9.6
          php_version: 8.1
          bootstrap: modules/registrars/realtimeregister/vendor/autoload.php
          configuration: modules/registrars/realtimeregister/test/phpunit.xml
          args: --coverage-text